#!/usr/bin/env python3
"""Turn Applesoft's keyword list into the table src/tokens.S.

    tools/gentokens.py > src/tokens.S

The list below is Applesoft's own token table, $80 to $EA in order. It is
written out here rather than typed into assembly because ninety-odd keywords
hand-entered as `asc` lines with hand-counted lengths is a place typos hide:
one wrong length byte highlights half a word and nothing says why.

WHAT IS LEFT OUT, AND WHY

The single-character operators -- + - * / ^ > = < and & -- are tokens to
Applesoft but are not reserved WORDS, and drawing them inverse would make an
expression look like a rash. They are dropped here. Everything alphabetic is
kept, including the ones ending in punctuation (HCOLOR=, HIMEM:, TAB(), because
those characters are part of the keyword and Applesoft will not accept the name
without them.

FIRST-LETTER DISPATCH

The editor matches at a position rather than rolling a match over every
keyword at once: ninety-five simultaneous candidates would be ninety-five
compares per character drawn, and a redraw touches seventeen hundred of them.
So the table is grouped by first letter and the generator emits an index --
where each letter's group starts, and how many are in it. A character that
begins no keyword costs one lookup and nothing else.

LONGEST FIRST

Within a letter the keywords are sorted longest first, so ATN is tried before
AT and RESTORE before RESUME... and before RETURN, which shares nothing but
its first two letters. Applesoft's own tokenizer works down its table in token
order and needs a special case to stop ATN being read as AT followed by N;
longest-first gets the same answer without one.
"""
import sys

# Applesoft's token table, $80-$EA, in order.
TOKENS = [
    "END", "FOR", "NEXT", "DATA", "INPUT", "DEL", "DIM", "READ", "GR", "TEXT",
    "PR#", "IN#", "CALL", "PLOT", "HLIN", "VLIN", "HGR2", "HGR", "HCOLOR=",
    "HPLOT", "DRAW", "XDRAW", "HTAB", "HOME", "ROT=", "SCALE=", "SHLOAD",
    "TRACE", "NOTRACE", "NORMAL", "INVERSE", "FLASH", "COLOR=", "POP", "VTAB",
    "HIMEM:", "LOMEM:", "ONERR", "RESUME", "RECALL", "STORE", "SPEED=", "LET",
    "GOTO", "RUN", "IF", "RESTORE", "&", "GOSUB", "RETURN", "REM", "STOP",
    "ON", "WAIT", "LOAD", "SAVE", "DEF", "POKE", "PRINT", "CONT", "LIST",
    "CLEAR", "GET", "NEW", "TAB(", "TO", "FN", "SPC(", "THEN", "AT", "NOT",
    "STEP", "+", "-", "*", "/", "^", "AND", "OR", ">", "=", "<", "SGN", "INT",
    "ABS", "USR", "FRE", "SCRN(", "PDL", "POS", "SQR", "RND", "LOG", "EXP",
    "COS", "SIN", "TAN", "ATN", "PEEK", "LEN", "STR$", "VAL", "ASC", "CHR$",
    "LEFT$", "RIGHT$", "MID$",
]

def main():
    assert len(TOKENS) == 107, f"the table is $80-$EA, which is 107, not {len(TOKENS)}"

    dropped = [t for t in TOKENS if not t[0].isalpha()]
    assert len(dropped) == 9, dropped     # & + - * / ^ > = <
    words = [t for t in TOKENS if t[0].isalpha()]
    assert len(words) == 98, len(words)

    # group by first letter, longest first inside each group
    groups = {}
    for w in words:
        groups.setdefault(w[0], []).append(w)
    for g in groups.values():
        g.sort(key=lambda w: (-len(w), w))

    order = []
    index = {}
    for letter in sorted(groups):
        index[letter] = (len(order), len(groups[letter]))
        order.extend(groups[letter])

    out = [
        "*" + "-" * 37,
        "* GENERATED by tools/gentokens.py -- DO NOT EDIT.",
        "*",
        "* Applesoft's keywords, grouped by first letter and longest first, with",
        "* an index so that a character which begins no keyword costs one lookup.",
        "* Edit tools/gentokens.py and rebuild.",
        "*" + "-" * 37,
        "",
        f"TKN          equ   {len(order)}",
        f"TKREMI       equ   {order.index('REM')}"  + "        ; REM ends the line for highlighting",
        "",
        "*--- for each letter A-Z: where its group starts, and how many",
        "TKFIRST      dfb   " + ",".join(str(index.get(chr(c), (0, 0))[0]) for c in range(ord("A"), ord("N"))),
        "             dfb   " + ",".join(str(index.get(chr(c), (0, 0))[0]) for c in range(ord("N"), ord("["))),
        "TKCOUNT      dfb   " + ",".join(str(index.get(chr(c), (0, 0))[1]) for c in range(ord("A"), ord("N"))),
        "             dfb   " + ",".join(str(index.get(chr(c), (0, 0))[1]) for c in range(ord("N"), ord("["))),
        "",
        "*--- each keyword's length, then a pointer to its text",
        "TKLEN        dfb   " + ",".join(str(len(w)) for w in order[:16]),
    ]
    for i in range(16, len(order), 16):
        out.append("             dfb   " + ",".join(str(len(w)) for w in order[i:i + 16]))

    out.append("")
    out.append("TKLO         dfb   " + ",".join(f"<TKW{i}" for i in range(min(8, len(order)))))
    for i in range(8, len(order), 8):
        out.append("             dfb   " + ",".join(f"<TKW{j}" for j in range(i, min(i + 8, len(order)))))
    out.append("TKHI         dfb   " + ",".join(f">TKW{i}" for i in range(min(8, len(order)))))
    for i in range(8, len(order), 8):
        out.append("             dfb   " + ",".join(f">TKW{j}" for j in range(i, min(i + 8, len(order)))))

    out.append("")
    out.append("*--- and the text itself, high ASCII")
    for i, w in enumerate(order):
        out.append(f'TKW{i}'.ljust(12) + f' asc   "{w}"')

    print("\n".join(out))

if __name__ == "__main__":
    main()
